# Country landing pages. Edit here, then run:  python3 tools/build_countries.py
# Arabic copy is written in each country's dialect; English is standard.
# The pages are reached from the region cards on the home page (and the sitemap).

COUNTRIES = [
{
  "slug": "egypt",
  "code": "EG",
  "ar": {
    "name": "مصر",
    "title": "تسويق إلكتروني وتصميم مواقع في مصر",
    "desc": "إعلانات ممولة، تصميم مواقع ومتاجر، إدارة سوشيال ميديا وتسجيل على جوجل ماب لمشاريع وشركات في كل محافظات مصر.",
    "lead": "بعملّك موقع وإعلانات وبدير صفحاتك على السوشيال ميديا، بكلام مصري قريب من قلب عميلك، في أي محافظة من إسكندرية لأسوان.",
    "services_h": "خدماتي لمشروعك في مصر",
    "services": [
      ("ads", "إعلانات ممولة", "حملات على فيسبوك وإنستجرام وتيك توك وجوجل، بتوصل لجمهورك في محافظتك بالظبط، وبميزانية إنت متحكم فيها."),
      ("web", "تصميم مواقع", "موقع سريع وشكله محترم على الموبايل، فيه زرار واتساب وفورم طلبات، ومجهّز يظهر في جوجل."),
      ("store", "متاجر إلكترونية", "متجر كامل بالسلة والطلبات والشحن، تديره بنفسك بسهولة من غير ما تحتاج حد."),
      ("social", "إدارة السوشيال ميديا", "تصميم بوستات وكتابة محتوى بالمصري، ونشر بانتظام، ورد على العملاء أول بأول."),
      ("maps", "تسجيل على جوجل ماب", "بسجّل نشاطك على خرايط جوجل عشان اللي حواليك يلاقوك ويتصلوا بيك على طول."),
      ("seo", "ظهور في جوجل (SEO)", "بظبطلك موقعك عشان يطلع في أول النتايج لما حد يدوّر على خدمتك في منطقتك."),
    ],
    "why_h": "ليه أنا لمشروعك؟",
    "why": [
      "فاهم السوق المصري والعروض والكلام اللي بيشد الناس.",
      "سعر واضح ومتفق عليه قبل ما نبدأ.",
      "بتتكلم معايا أنا على طول على واتساب، من غير وسطاء.",
    ],
    "faq": [
      ("بتشتغل مع مشاريع برا القاهرة؟", "أيوه، الشغل كله أونلاين، فمش فارق إنت في أنهي محافظة. بنتابع مع بعض على واتساب خطوة بخطوة."),
      ("ينفع أبدأ بميزانية إعلانات صغيرة؟", "أكيد. بنبدأ بميزانية صغيرة نجرّب بيها، ولما النتايج تبان نكبّر على اللي شغال."),
    ],
    "cta_h": "يلا نبدأ مشروعك؟",
    "cta_p": "ابعتلي على واتساب وقولّي محتاج إيه، وهرد عليك بسرعة.",
    "wa_text": "أهلاً وليد، جاي من صفحة مصر في موقعك وعايز أستفسر عن خدمة",
  },
  "en": {
    "name": "Egypt",
    "title": "Digital marketing & web design in Egypt",
    "desc": "Paid ads, websites and online stores, social media management and Google Maps listings for businesses across Egypt.",
    "lead": "Websites, ads and social media for projects and companies across Egypt — from Alexandria to Aswan — written in the Egyptian voice your customers trust.",
    "services_h": "What I do for businesses in Egypt",
    "services": [
      ("ads", "Paid ads", "Campaigns on Facebook, Instagram, TikTok and Google that reach your audience in your governorate, on a budget you control."),
      ("web", "Website design", "A fast, polished mobile-first site with a WhatsApp button and order form, ready to show up on Google."),
      ("store", "Online stores", "A complete store with cart, orders and shipping that you can run yourself."),
      ("social", "Social media management", "Post design, Egyptian-Arabic copywriting, a steady publishing schedule and replies to customers."),
      ("maps", "Google Maps listing", "Your business on Google Maps so nearby customers can find and call you."),
      ("seo", "Google visibility (SEO)", "Your site tuned to rank when people nearby search for what you offer."),
    ],
    "why_h": "Why work with me?",
    "why": [
      "I understand the Egyptian market and the offers and wording that get people to act.",
      "A clear, agreed price before we start.",
      "You talk to me directly on WhatsApp — no middlemen.",
    ],
    "faq": [
      ("Do you work with businesses outside Cairo?", "Yes. All the work is online, so your governorate doesn't matter. We follow up on WhatsApp step by step."),
      ("Can I start with a small ad budget?", "Of course. We start small to test, then scale what works once results show."),
    ],
    "cta_h": "Ready to start?",
    "cta_p": "Message me on WhatsApp with what you need and I'll get back to you quickly.",
    "wa_text": "Hi Waled, I found your Egypt page and I'd like to ask about a service",
  },
},
{
  "slug": "libya",
  "code": "LY",
  "ar": {
    "name": "ليبيا",
    "title": "تسويق إلكتروني وتصميم مواقع في ليبيا",
    "desc": "إعلانات ممولة، تصميم مواقع ومتاجر، إدارة صفحات السوشيال ميديا وتسجيل على خرايط جوجل لمشاريع وشركات في ليبيا.",
    "lead": "نديرولك موقع وإعلانات ممولة تجيبلك زبائن هلبا، بكلام ليبي يفهمه زبونك ويرتاحله، من طرابلس لبنغازي ومصراتة وسبها.",
    "services_h": "شن نديرولك في ليبيا؟",
    "services": [
      ("ads", "إعلانات ممولة", "حملات على فيسبوك وإنستجرام وتيك توك، نوصّلو بيها لزبونك في مدينتك بالضبط، وتعرف كل دينار وين مشى."),
      ("web", "تصميم مواقع", "موقع باهي وسريع على الموبايل، فيه زر واتساب وفورم طلبات، يخلّي زبونك يثق فيك من أول نظرة."),
      ("store", "متاجر إلكترونية", "متجر إلكتروني بالسلة والطلبات، تديره بروحك بكل سهولة."),
      ("social", "صفحات السوشيال ميديا", "نصمّمو بوستاتك ونكتبو المحتوى بالليبي، وننزلوه بانتظام، ونردو على زبائنك."),
      ("maps", "تسجيل على خرايط جوجل", "نسجّلو محلك على خرايط جوجل باش اللي قريب منك يلقاك ويكلمك طول."),
      ("seo", "ظهور في جوجل (SEO)", "نظبطولك موقعك باش يطلع في أول النتايج لما حد يدوّر على خدمتك."),
    ],
    "why_h": "علاش تختارني؟",
    "why": [
      "نفهم السوق الليبي وشن اللي يشد الزبون.",
      "سعر واضح ومتفق عليه قبل ما نبدو.",
      "تتكلم معاي أنا طول على الواتساب، من غير وسيط.",
    ],
    "faq": [
      ("تخدم مع ناس في ليبيا وأنت برا؟", "إيه، الخدمة كلها أونلاين، ونتابعو مع بعض على الواتساب خطوة بخطوة."),
      ("نقدر نبدا بميزانية إعلانات صغيرة؟", "باهي، نبدو بميزانية صغيرة نجربو بيها، ولما النتايج تبان نكبرو على اللي ماشي."),
    ],
    "cta_h": "توا نبدو مشروعك؟",
    "cta_p": "ابعتلي على الواتساب وقولي شن تبي، ونرد عليك بسرعة.",
    "wa_text": "مرحبا وليد، جاي من صفحة ليبيا في موقعك ونبي نسأل على خدمة",
  },
  "en": {
    "name": "Libya",
    "title": "Digital marketing & web design in Libya",
    "desc": "Paid ads, websites and online stores, social media management and Google Maps listings for businesses in Libya.",
    "lead": "Websites and paid ads that bring real customers, with content that speaks to Libyan audiences — from Tripoli to Benghazi, Misrata and Sabha.",
    "services_h": "What I do for businesses in Libya",
    "services": [
      ("ads", "Paid ads", "Campaigns on Facebook, Instagram and TikTok that reach customers in your city, with every dinar accounted for."),
      ("web", "Website design", "A fast, good-looking mobile site with a WhatsApp button and order form that builds trust at first glance."),
      ("store", "Online stores", "An online store with cart and orders that you can run yourself."),
      ("social", "Social media pages", "Post design, Libyan-Arabic copywriting, regular publishing and replies to your customers."),
      ("maps", "Google Maps listing", "Your shop on Google Maps so nearby customers can find and call you."),
      ("seo", "Google visibility (SEO)", "Your site tuned to rank when people search for what you offer."),
    ],
    "why_h": "Why work with me?",
    "why": [
      "I understand the Libyan market and what gets customers to act.",
      "A clear, agreed price before we start.",
      "You talk to me directly on WhatsApp — no middlemen.",
    ],
    "faq": [
      ("Do you work with clients in Libya remotely?", "Yes. All the work is online and we follow up on WhatsApp step by step."),
      ("Can I start with a small ad budget?", "Sure. We start small to test, then scale what works once results show."),
    ],
    "cta_h": "Ready to start?",
    "cta_p": "Message me on WhatsApp with what you need and I'll get back to you quickly.",
    "wa_text": "Hi Waled, I found your Libya page and I'd like to ask about a service",
  },
},
{
  "slug": "kuwait",
  "code": "KW",
  "ar": {
    "name": "الكويت",
    "title": "تسويق إلكتروني وتصميم مواقع في الكويت",
    "desc": "إعلانات ممولة، تصميم مواقع ومتاجر، إدارة سوشيال ميديا وتسجيل على خرائط جوجل لشركات ومحلات في كل محافظات الكويت.",
    "lead": "أسوي لكم مواقع وحملات لشركاتكم ومحلاتكم، بمحتوى كويتي يوصل لعميلكم وايد زين، من العاصمة لحولي والفروانية والأحمدي والجهراء ومبارك الكبير.",
    "services_h": "شنو أسوي لكم في الكويت؟",
    "services": [
      ("ads", "إعلانات ممولة", "حملات على إنستغرام وسناب شات وتيك توك وجوجل، تستهدف المناطق اللي تبونها بالضبط، وتعرفون وين راحت كل فلس."),
      ("web", "تصميم مواقع", "موقع سريع وشكله راقي على التلفون، فيه زر واتساب وطلبات، ويطلع لكم في جوجل."),
      ("store", "متاجر إلكترونية", "متجر إلكتروني كامل بالسلة والدفع والتوصيل، تديرونه بنفسكم بكل سهولة."),
      ("social", "إدارة السوشيال ميديا", "تصاميم ومحتوى بالكويتي، ونشر منتظم، ورد على عملائكم أول بأول."),
      ("maps", "تسجيل على خرائط جوجل", "أسجّل محلكم على خرائط جوجل عشان اللي بالمنطقة يلقونكم ويتصلون فيكم على طول."),
      ("seo", "ظهور في جوجل (SEO)", "أضبط موقعكم عشان يطلع بأول النتايج لما أحد يدوّر على خدمتكم."),
    ],
    "why_h": "ليش تختاروني؟",
    "why": [
      "أفهم السوق الكويتي وشنو اللي يجذب العميل.",
      "سعر واضح ومتفق عليه قبل لا نبدأ.",
      "تتواصلون معاي أنا مباشرة على الواتساب، بدون وسيط.",
    ],
    "faq": [
      ("تشتغل مع شركات بالكويت وانت برا؟", "إي نعم، الشغل كله أونلاين، ونتابع ويا بعض على الواتساب خطوة بخطوة."),
      ("أقدر أبدأ بميزانية إعلانات بسيطة؟", "أكيد، نبدأ بميزانية بسيطة نجرب فيها، وإذا بانت النتايج نكبّر اللي شغال."),
    ],
    "cta_h": "نبدأ مشروعكم الحين؟",
    "cta_p": "راسلوني على الواتساب وقولوا لي شنو تحتاجون، وأرد عليكم بسرعة.",
    "wa_text": "هلا وليد، جاي من صفحة الكويت في موقعك وأبي أستفسر عن خدمة",
  },
  "en": {
    "name": "Kuwait",
    "title": "Digital marketing & web design in Kuwait",
    "desc": "Paid ads, websites and online stores, social media management and Google Maps listings for companies and shops across Kuwait.",
    "lead": "Websites and campaigns for companies and shops in Kuwait, with content in the Kuwaiti voice and precise targeting across every governorate — Capital, Hawalli, Farwaniya, Ahmadi, Jahra and Mubarak Al-Kabeer.",
    "services_h": "What I do for businesses in Kuwait",
    "services": [
      ("ads", "Paid ads", "Campaigns on Instagram, Snapchat, TikTok and Google that target exactly the areas you want, with every fils accounted for."),
      ("web", "Website design", "A fast, premium mobile site with a WhatsApp button and orders, ready to show up on Google."),
      ("store", "Online stores", "A complete store with cart, payment and delivery that you can run yourself."),
      ("social", "Social media management", "Designs and Kuwaiti-Arabic content, regular publishing and replies to your customers."),
      ("maps", "Google Maps listing", "Your shop on Google Maps so people in your area can find and call you."),
      ("seo", "Google visibility (SEO)", "Your site tuned to rank when people search for what you offer."),
    ],
    "why_h": "Why work with me?",
    "why": [
      "I understand the Kuwaiti market and what attracts customers.",
      "A clear, agreed price before we start.",
      "You talk to me directly on WhatsApp — no middlemen.",
    ],
    "faq": [
      ("Do you work with companies in Kuwait remotely?", "Yes. All the work is online and we follow up on WhatsApp step by step."),
      ("Can I start with a small ad budget?", "Of course. We start small to test, then scale what works once results show."),
    ],
    "cta_h": "Ready to start?",
    "cta_p": "Message me on WhatsApp with what you need and I'll get back to you quickly.",
    "wa_text": "Hi Waled, I found your Kuwait page and I'd like to ask about a service",
  },
},
{
  "slug": "gulf",
  "code": "GCC",
  "ar": {
    "name": "دول الخليج",
    "title": "تسويق إلكتروني وتصميم مواقع في السعودية والإمارات وقطر والبحرين وعُمان",
    "desc": "إعلانات ممولة، تصميم مواقع ومتاجر، إدارة سوشيال ميديا وتسجيل على خرائط جوجل لعملاء في السعودية والإمارات وقطر والبحرين وعُمان.",
    "lead": "حيّاكم الله.. أسوي لكم حملات ومحتوى ومواقع تناسب كل سوق في الخليج، من الرياض وجدة لدبي والدوحة والمنامة ومسقط، وتخاطب عميلكم بالأسلوب اللي يحبه.",
    "services_h": "وش أقدر أسوي لكم؟",
    "services": [
      ("ads", "إعلانات ممولة", "حملات على سناب شات وإنستغرام وتيك توك وجوجل، تستهدف مدينتكم وعميلكم بالضبط، وتعرفون وين راحت ميزانيتكم."),
      ("web", "تصميم مواقع", "موقع سريع وفخم على الجوال، فيه زر واتساب وطلبات، ومجهّز يطلع في جوجل."),
      ("store", "متاجر إلكترونية", "متجر إلكتروني متكامل بالسلة والدفع والشحن، تديرونه بأنفسكم بسهولة."),
      ("social", "إدارة السوشيال ميديا", "تصاميم ومحتوى يناسب ثقافة كل بلد، ونشر منتظم، ورد على عملائكم أول بأول."),
      ("maps", "تسجيل على خرائط جوجل", "أسجّل نشاطكم على خرائط جوجل عشان اللي حولكم يلقونكم ويتواصلون معكم مباشرة."),
      ("seo", "ظهور في جوجل (SEO)", "أضبط موقعكم عشان يطلع بأول النتايج لما أحد يدوّر على خدمتكم."),
    ],
    "why_h": "ليش تختاروني؟",
    "why": [
      "أفهم الفرق بين كل سوق خليجي ووش يناسبه.",
      "سعر واضح ومتفق عليه قبل لا نبدأ.",
      "تتواصلون معاي أنا مباشرة على الواتساب، بدون وسيط.",
    ],
    "faq": [
      ("تشتغل مع عملاء في السعودية والإمارات وانت برا؟", "إيه، الشغل كله أونلاين، ونتابع مع بعض على الواتساب خطوة بخطوة."),
      ("أقدر أبدأ بميزانية إعلانات بسيطة؟", "أكيد، نبدأ بميزانية بسيطة نجرب فيها، وإذا بانت النتايج نكبّر اللي شغال."),
    ],
    "cta_h": "نبدأ مشروعكم؟",
    "cta_p": "راسلوني على الواتساب وقولوا لي وش تحتاجون، وأرد عليكم بسرعة.",
    "wa_text": "مرحبا وليد، جاي من صفحة الخليج في موقعك وأبي أستفسر عن خدمة",
  },
  "en": {
    "name": "the Gulf",
    "title": "Digital marketing & web design in Saudi Arabia, the UAE, Qatar, Bahrain and Oman",
    "desc": "Paid ads, websites and online stores, social media management and Google Maps listings for clients in Saudi Arabia, the UAE, Qatar, Bahrain and Oman.",
    "lead": "Campaigns, content and websites tailored to each Gulf market — from Riyadh and Jeddah to Dubai, Doha, Manama and Muscat — speaking to your customers the way they like.",
    "services_h": "What I do for businesses in the Gulf",
    "services": [
      ("ads", "Paid ads", "Campaigns on Snapchat, Instagram, TikTok and Google that target your city and customer precisely, with clear reporting on spend."),
      ("web", "Website design", "A fast, premium mobile site with a WhatsApp button and orders, ready to show up on Google."),
      ("store", "Online stores", "A complete store with cart, payment and shipping that you can run yourself."),
      ("social", "Social media management", "Designs and content suited to each country's culture, regular publishing and replies to customers."),
      ("maps", "Google Maps listing", "Your business on Google Maps so people nearby can find and contact you."),
      ("seo", "Google visibility (SEO)", "Your site tuned to rank when people search for what you offer."),
    ],
    "why_h": "Why work with me?",
    "why": [
      "I understand how each Gulf market differs and what suits it.",
      "A clear, agreed price before we start.",
      "You talk to me directly on WhatsApp — no middlemen.",
    ],
    "faq": [
      ("Do you work with clients in Saudi Arabia and the UAE remotely?", "Yes. All the work is online and we follow up on WhatsApp step by step."),
      ("Can I start with a small ad budget?", "Of course. We start small to test, then scale what works once results show."),
    ],
    "cta_h": "Ready to start?",
    "cta_p": "Message me on WhatsApp with what you need and I'll get back to you quickly.",
    "wa_text": "Hi Waled, I found your Gulf page and I'd like to ask about a service",
  },
},
]
